#pragma once
#include "stdafx.h"

enum class ARCHER_ANIMATION : UINT8
{
	WALKFAST,
	WALK,
	SKILLATTACK,
	RUNR,
	RUNL,
	RUNBACK,
	RUNATTACK,
	RUN,
	JUMP,
	IDLE,
	GETHIT,
	GATHERING,
	FALL,
	DEATH,
	COMBATIDLE,
	BLOCKINGLOOP,
	BLOCKING,
	ATTACK,
	__STATIC_POSE,

	end
};

enum class FIGHTER_ANIMATION : UINT8
{
	WALK,
	SKILLATTACK,
	RUNR,
	RUNL,
	RUN,
	RUNBACK,
	RUNATTACK,
	JUMP,
	IDLE,
	GETHIT,
	GATHERING,
	FALLING,
	DEATH,
	COMBATIDLE,
	CASTINGLOOP,
	BUFF,
	BLOCKINGLOOP,
	ATTACK,
	_STATIC_POSE,

	end
};

enum class MAGE_ANIMATION : UINT8
{
	WALK,
	SKILLATTACK,
	RUNR,
	RUNL,
	RUNBACK,
	RUNATTACK,
	RUN,
	JUMP,
	IDLE,
	GETHIT,
	GATHERING,
	FALLING,
	DEATH,
	COMBATIDLE,
	CASTINGLOOP,
	BUFF,
	BLOCKINGLOOP,
	ATTACK,
	__STATIC_POSE,

	end
};

std::unordered_map<PLAYER_STATE, ARCHER_ANIMATION> ARCHER_MAP = {
	{ PLAYER_STATE::IDLE, ARCHER_ANIMATION::IDLE },
	{ PLAYER_STATE::RUN, ARCHER_ANIMATION::RUN },
	{ PLAYER_STATE::ATTACK, ARCHER_ANIMATION::ATTACK },
	{ PLAYER_STATE::MOVE_ATTACK, ARCHER_ANIMATION::RUNATTACK },
	{ PLAYER_STATE::GETHIT, ARCHER_ANIMATION::GETHIT },
	{ PLAYER_STATE::DEATH, ARCHER_ANIMATION::DEATH },
	{ PLAYER_STATE::JUMP, ARCHER_ANIMATION::JUMP },
	{ PLAYER_STATE::SKILL, ARCHER_ANIMATION::SKILLATTACK }
};

std::unordered_map<PLAYER_STATE, FIGHTER_ANIMATION> FIGHTER_MAP = {
	{ PLAYER_STATE::IDLE, FIGHTER_ANIMATION::IDLE },
	{ PLAYER_STATE::RUN, FIGHTER_ANIMATION::RUN },
	{ PLAYER_STATE::ATTACK, FIGHTER_ANIMATION::ATTACK },
	{ PLAYER_STATE::MOVE_ATTACK, FIGHTER_ANIMATION::RUNATTACK },
	{ PLAYER_STATE::GETHIT, FIGHTER_ANIMATION::GETHIT },
	{ PLAYER_STATE::DEATH, FIGHTER_ANIMATION::DEATH },
	{ PLAYER_STATE::JUMP, FIGHTER_ANIMATION::JUMP },
	{ PLAYER_STATE::SKILL, FIGHTER_ANIMATION::SKILLATTACK }
};

std::unordered_map<PLAYER_STATE, MAGE_ANIMATION> MAGE_MAP = {
	{ PLAYER_STATE::IDLE, MAGE_ANIMATION::IDLE },
	{ PLAYER_STATE::RUN, MAGE_ANIMATION::RUN },
	{ PLAYER_STATE::ATTACK, MAGE_ANIMATION::ATTACK },
	{ PLAYER_STATE::MOVE_ATTACK, MAGE_ANIMATION::RUNATTACK },
	{ PLAYER_STATE::GETHIT, MAGE_ANIMATION::GETHIT },
	{ PLAYER_STATE::DEATH, MAGE_ANIMATION::DEATH },
	{ PLAYER_STATE::JUMP, MAGE_ANIMATION::JUMP },
	{ PLAYER_STATE::SKILL, MAGE_ANIMATION::SKILLATTACK }
};